preferences:
  theme: light
devices:
  MODULE_01:
    name: Terrace
    settings:
      defaultVolume: 50            # Default volume of water par output
      defaultRatio: 2              # Mililiters per second
      maxVolumePerOutput: 1000     # Max volume of water per output
    type: MCP23017
    address: 39                    # I2C address of the device
    outputs:
      '1':
        pin: 8
      '2':
        pin: 6
      '3':
        pin: 9
      '4':
        pin: 5
      '5':
        pin: 10
      '6':
        pin: 4
      '7':
        pin: 11
      '8':
        pin: 3
      '9':
        pin: 12
      '10':
        pin: 2
      '11':
        pin: 13
      '12':
        pin: 1
      '13':
        pin: 14
      '14':
        pin: 0
      pump:
        pin: 7
    inputs: {}
